### PR TITLE
vary array lengths so indices can't be hard-coded

### PR DESCRIPTION
**Pull request by mwoguri**
One of my students was making the tests pass by hard-coding indices  😐 😞

### CODE REVIEW

**Comment by mwoguri** [comment]
@keithagroves I'm not familiar with github classroom.  Did I make this PR correctly?

Edit: I think this isn't going to work since `level3-module0-mwoguri` isn't a fork of `League-level3-student`.

**Comment by keithagroves** [comment]
Hi Michiyo,

That's right. You should make a fork of the repo [https://github.com/League-level3/L3_Module_0](https://github.com/League-level3/L3_Module_0). You can copy the code that you have to the new fork. Github classrooms creates a sandbox duplicate of this repository.

Best,
Keith

**Comment by mwoguri** [comment]
Thanks @keithagroves.  Is https://github.com/League-level3/L3_Module_0 definitely the right repo?  I ask because I can't find the packages/recipes that my class did.  There doesn't seem to be a `_01_Simple_Array_Algorithms/_00_1D_Array_Test.java`, for example.

**Comment by keithagroves** [comment]
Hey Michiyo, Sorry, we need to work on our naming conventions. I sent you the old module. Here is the right repo [https://github.com/League-level3/_00_Arrays](https://github.com/League-level3/_00_Arrays)

edit: Also, all the repos are located here: [https://github.com/League-level3](https://github.com/League-level3)

**Comment by mwoguri** [comment]
I hope I created this correctly [here](https://github.com/League-level3/_00_Arrays/pull/1).

**Pull request closed without merging**
